### ISSUE TITLE
Run error in 64 win 7

### ISSUE THREAD

**Issue by Aliceljm1** [lrscp/AndroidLogViewer#1]
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
    at org.eclipse.swt.widgets.Widget.<clinit>(Unknown Source)

**Comment by dongweiq** [comment]
64 win10 too

**Comment by grf123** [comment]
repleace  32-bit swt.
http://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.8-201806110500/swt-4.8-win32-win32-x86_64.zip&mirror_id=105
